name: Lần Hồi
description: Dự án nghệ thuật cộng đồng Lần Hồi - Mượn rung cảm thời gian.
url: http://lanhoi.org
permalink: pretty
prose:
  rooturl: "news/_posts"
  metadata:
    "news/_posts": |
      layout: post
      title: "tiêu đề"
      description: "miêu tả ngắn gọn"
      thumb: "link ảnh minh họa"
      lead: "đoạn mở đầu"
      published: false
